# Foundry Configuration File
# See more config options at: https://github.com/foundry-rs/foundry/tree/master/config

# The Default Profile
[profile.default]
# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
solc_version = '0.8.15'
auto_detect_solc = false
# Increase optimizer_runs
optimizer = true
optimizer_runs = 1_000
# Fuzz more than the default 256
fuzz_runs = 1_000
# Path defaults
libs = ['lib']
src = 'src'
test = 'test'
out = 'out'

# Extreme Fuzzing CI Profile
[profile.ci]
fuzz_runs = 5_000

# Profile For Deployments
[profile.deploy]
optimizer = true
optimizer_runs = 1_000_000

# RPC Endpoints
[rpc_endpoints]
mainnet = "${RPC_MAINNET_URL}"